# Generated by Django 3.0.6 on 2020-06-02 21:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_auto_20200602_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=tinymce.models.HTMLField(max_length=5000),
        ),
    ]
