# Generated by Django 3.0.7 on 2020-09-24 23:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_auto_20200602_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=tinymce.models.HTMLField(max_length=30000),
        ),
    ]
